version: '3.6'

services:
  testsysplan.api:  
    environment:  
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      #http
      - "8080:80"
      #https
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  testsysplan.sqldb:  
     ports:
      - "1401:1433"