version: '3.7'

networks:
  testsysplan-network:
    driver: bridge

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
  mssqldb:  
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=#p@$$w04d
      - MSSQL_SA_PASSWORD=#p@$$w04d
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    networks:
      - testsysplan-network
    ports:
      - "1401:1433"
    
  testsysplan.api:
    container_name: testsysplan.api
    image: ${DOCKER_REGISTRY-}testsysplanapi
    build:
      context: .
      dockerfile: TestSysplan.API/Dockerfile
    environment:      
      - DATABASE_LOCAL_NAME=TesteDb
      - DATABASE_LOCAL_HOST=localhost
      - DATABASE_LOCAL_PORT=1401
      - DATABASE_LOCAL_USER=sa
      - DATABASE_LOCAL_PSWD=#p@$$w04d
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - testsysplan-network
    ports:
      #http
      - "8080:80"
      #https
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - elasticsearch
      - mssqldb

volumes:
  esdata:
    driver: local  