version: '3.7'

services:
  
  elasticsearch:
    environment:
      #Enable to monitoring Elasticsearch.
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  mssqldb:  
    ports:
      - "1401:1433"
    
  testsysplan.api:  
    environment:  
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_LOCAL_HOST=host.docker.internal
    ports:
      #http
      - "8080:80"
      #https
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  esdata:
    driver: local  